<?php

namespace SprintBundle\Repository;

/**
 * SprintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SprintRepository extends \Doctrine\ORM\EntityRepository
{
    public function getD($user,$date)
    {


        $qb = $this->createQueryBuilder("e");
        $qb ->Join('ScrumBundle:Projet','p' )
            ->Join('TeamBundle:team_user','t' )
            ->andWhere('e.project = p.id ' )
            ->andWhere('p.team = t.teamId')
            ->andWhere('t.userId = :user' )
            ->andWhere('e.duedate = :date ')
            ->andWhere('e.etat = 1')
            ->setParameters(array('date'=>$date , 'user'=>$user) );

        return $result = $qb->getQuery()->getResult();


    }
}
