activity_homepage:
    path:     /afficher_activite
    defaults: { _controller: ActivityBundle:Activity:Afficher }
delete_activity:
    path:     /delete_activity
    defaults: { _controller: ActivityBundle:Activity:Supprimer}
ChangeActivityState:
    path:   /change_activity
    defaults: { _controller: ActivityBundle:Activity:ChangeActivityState}
getNotif:
    path:   /getNotif
    defaults: { _controller: ActivityBundle:Activity:getNotif}
    methods: [post]
ajoutermeeting:
    path:     /ajouter_meetings
    defaults: { _controller: ActivityBundle:Meetings:ajouter }
affichermeeting:
    path:     /afficher_meetings/{id}
    defaults: { _controller: ActivityBundle:Meetings:AfficheMetting }
delete_meeting:
    path:      /Meeting/delete/{id}
    defaults: { _controller: ActivityBundle:Meetings:Supprimer}
update_meeting:
    path:     /update_meeting/{id}
    defaults: { _controller: ActivityBundle:Meetings:modifier}
ajouterMeeting:
    path:   /Meeting/Add
    defaults: { _controller: ActivityBundle:Meetings:ajouterMeeting}