tasks_homepage:
    path:     /home
    defaults: { _controller: TasksBundle:Default:home }
add_tasks:
    path:     /addTasks
    defaults: { _controller: TasksBundle:Tasks:addTasks }
show_tasks:
    path:     /showTasks/{id}
    defaults: { _controller: TasksBundle:Tasks:showTasks }
edit_tasks:
    path:     /editTasks/{Id}
    defaults: { _controller: TasksBundle:Service:edit }
archiver_tasks:
    path:     /archiveTasks/{id}
    defaults: { _controller: TasksBundle:Service:archive }
statut_task:
    path:     /statutTask/{id}/{statut}
    defaults: { _controller: TasksBundle:Tasks:changeStatus }
desarchiver:
    path:     /desarchive/{id}
    defaults: { _controller: TasksBundle:Tasks:desarchiver }
show_tasks_back:
    path:   /showBack
    defaults: { _controller: TasksBundle:Tasks:showTasksB }
affecterUserTask:
    path:   /aff/{task_id}/{user_id}
    defaults: { _controller: TasksBundle:Default:affUserTask }
Taskaffmobile:
    path:   /show
    defaults: { _controller: TasksBundle:Service:show }
addTaskmobile:
    path:   /new
    defaults: { _controller: TasksBundle:Service:new }
showDoing:
    path:   /showDoing
    defaults: { _controller: TasksBundle:Service:showDoing }
showTodo:
    path:   /showTodo
    defaults: { _controller: TasksBundle:Service:showTodo }
showDone:
    path:   /showDone
    defaults: { _controller: TasksBundle:Service:showDone }
showBlock:
    path:   /showBlock
    defaults: { _controller: TasksBundle:Service:showBlock }