<?php

namespace MessagingBundle\Repository;

/**
 * FriendShipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendShipRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFriends($user)
    {

        $qb = $this->getEntityManager()
       ->createQuery("SELECT t
                                     FROM MainBundle\Entity\User t , MessagingBundle\Entity\FriendShip e
                                     WHERE t.id = e.friend and e.user = :user and e.isFriend = 1");
        $qb->setParameter('user', $user);
        $result = $qb->getOneOrNullResult();
        return $result;



    }
}
