<?php

namespace TasksBundle\Repository;

/**
 * TasksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TasksRepository extends \Doctrine\ORM\EntityRepository
{
   /* public function affect($user_id,$task_id){
        $qb = $this->createQueryBuilder("e");
        $qb ->('TeamBundle:team_user','t' )
            ->andWhere('t.userId = :user' )
            ->andWhere('e.team = t.teamId')
            ->andWhere('e.etat = 1')
            ->setParameter('user',$user );
        return $result = $qb->getQuery()->getResult();

    }*/
}
