<?php

namespace ActivityBundle\Repository;


use TeamBundle\Entity\team;
use TeamBundle\Repository\teamRepository;

/**
 * ActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityRepository extends \Doctrine\ORM\EntityRepository
{

    public function findActivities($user)
    {


            $qb = $this->createQueryBuilder("e");
            $qb->select('e')
                ->join('TeamBundle:team_user', 't', 'WITH', 't.userId = :user')
                ->setParameter('user', $user);
        return    $result = $qb->getQuery()->getResult();


    }
}
